const $=id=>document.getElementById(id);
const loginView=$("loginView"),appView=$("appView"),loginForm=$("loginForm"),loginButton=$("loginButton"),loginMessage=$("loginMessage"),appMessage=$("appMessage");
const money=(v,c)=>{try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c,currencyDisplay:"code",minimumFractionDigits:2}).format(Number(v||0))}catch{return `${c} ${Number(v||0).toFixed(2)}`}};
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function message(text){appMessage.textContent=text||"";appMessage.classList.toggle("hidden",!text)}
function view(session){const on=!!session?.user;loginView.classList.toggle("hidden",on);appView.classList.toggle("hidden",!on);$("signedInUser").textContent=on?`Signed in as ${session.user.email}`:""}
function aggregate(rows){const map=new Map();for(const r of rows){const k=[r.lender_name,r.borrower_name,r.currency].join("|");if(!map.has(k))map.set(k,{lender:r.lender_name,borrower:r.borrower_name,currency:r.currency,principal:0,repaid:0,remaining:0,statuses:new Set});const x=map.get(k);x.principal+=Number(r.principal_amount||0);x.repaid+=Number(r.total_repaid||0);x.remaining+=Number(r.remaining_amount||0);x.statuses.add(r.calculated_status||"active")}return [...map.values()].map(x=>({...x,status:x.remaining<=0?"paid":x.statuses.has("overdue")?"overdue":"active"}))}
function renderAccounts(rows){$("accountsList").innerHTML=rows.map(a=>`<article class="account"><h3>${esc(a.account_name)}</h3><small>Owner: ${esc(a.owner_name)}${a.holder_name?` · Held by ${esc(a.holder_name)}`:""}</small><div class="values"><div class="value"><span>Total managed</span><strong>${money(a.total_managed_balance,a.currency)}</strong></div><div class="value"><span>Loans</span><strong>${money(a.outstanding_loans,a.currency)}</strong></div><div class="value"><span>Available</span><strong>${money(a.available_balance,a.currency)}</strong></div></div></article>`).join("")||"No accounts found."}
function renderLoans(rows){const data=aggregate(rows).sort((a,b)=>a.lender.localeCompare(b.lender)||a.borrower.localeCompare(b.borrower));$("loansTableBody").innerHTML=data.map(x=>`<tr><td>${esc(x.lender)}</td><td>${esc(x.borrower)}</td><td>${money(x.principal,x.currency)}</td><td>${money(x.repaid,x.currency)}</td><td><strong>${money(x.remaining,x.currency)}</strong></td><td><span class="badge ${x.status}">${x.status[0].toUpperCase()+x.status.slice(1)}</span></td></tr>`).join("")||'<tr><td colspan="6">No loans found.</td></tr>'}
async function load(){message("");$("refreshButton").disabled=true;try{const [a,l,p]=await Promise.all([supabaseClient.from("account_balances").select("*").order("account_name"),supabaseClient.from("loan_balances").select("*").order("created_at",{ascending:false}),supabaseClient.from("personal_money_position").select("*")]);const err=a.error||l.error||p.error;if(err)throw err;const accounts=a.data||[],positions=p.data||[];const dad=accounts.find(x=>x.account_name==="Dad's Money"),mal=accounts.find(x=>x.account_name==="Mal's Dollar Savings"),mvr=positions.find(x=>x.currency==="MVR");$("dadTotal").textContent=money(dad?.total_managed_balance,"MVR");$("dadAvailable").textContent=money(dad?.available_balance,"MVR");$("dadLoaned").textContent=money(dad?.outstanding_loans,"MVR");$("malSavings").textContent=money(mal?.available_balance,"USD");$("iOwe").textContent=money(mvr?.i_owe,"MVR");$("owedToMe").textContent=money(mvr?.owed_to_me,"MVR");renderAccounts(accounts);renderLoans(l.data||[])}catch(e){console.error(e);message(e.message||"Could not load dashboard.")}finally{$("refreshButton").disabled=false}}
loginForm.addEventListener("submit",async e=>{e.preventDefault();loginButton.disabled=true;loginMessage.textContent="";const {error}=await supabaseClient.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)loginMessage.textContent=error.message;else loginForm.reset();loginButton.disabled=false});
$("logoutButton").addEventListener("click",()=>supabaseClient.auth.signOut());$("refreshButton").addEventListener("click",load);
supabaseClient.auth.onAuthStateChange((_event,session)=>{view(session);if(session)load()});
(async()=>{if(SUPABASE_URL.includes("YOUR_PROJECT_REF")||SUPABASE_PUBLISHABLE_KEY==="YOUR_PUBLISHABLE_KEY"){loginMessage.textContent="Open config.js and add your Supabase URL and publishable key.";return}const {data:{session},error}=await supabaseClient.auth.getSession();if(error){loginMessage.textContent=error.message;return}view(session);if(session)await load()})();
